apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
spec:
  replicas: 20
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: usernode-js
        image: saiteja2502/userprofileretail:latest
        ports:
        - containerPort: 3130  # Change to match your app's port
        env:
        - name: MONGODB-URI
          value: "mongodb://mongodb:27017/myDatabase"  # Match this to your MongoDB deployment
        - name: SESSION-SECRET
          value: "1234"
        - name: EMAIL-USER
          value: "chagantyteja2502@gmail.com"
        - name: EMAIL-PASS
          value: "yxoq bjuk rdnt alzp"
        - name: PORT
          value: "3130"
